version: 0.2

phases:
  build:
    commands: 
      - echo "Performing Git CICD Operations"
      - git config --global user.name "subhomayb"
      - git config --global user.email "subhomay@me.com"
      - git clone -b $GIT_BRANCH https://$GIT_TOKEN@$GIT_URL
      - cd $DIRECTORY
      - git checkout $GIT_BRANCH
      - git pull
      - git remote add codecommit $REPO_NAME
      - git config credential.helper '!aws codecommit credential-helper $@'
      - git config credential.UseHttpPath true
      - git push codecommit $GIT_BRANCH

